[package]
name = "rid"
version = "0.1.0"
edition = "2021"
authors = ["Ayman Al-Qadhi <alqd@protonmail.com>"]

[workspace]
members = [ "data", "data/migration", "data/entity" ]

[dependencies]
data = { path = "./data" }
