[package]
name = "rid"
version = "0.1.0"
edition = "2021"
authors = ["Ayman Al-Qadhi <alqd@protonmail.com>"]

[workspace]
members = ["data", "data/migration", "data/entity"]

[workspace.dependencies]
uuid = "1.2.0"
async-trait = "0.1.57"

[dependencies]
data = { path = "./data" }
