[package]
name = "rid"
version = "0.1.0"
edition = "2021"
authors = ["Ayman Al-Qadhi <alqd@protonmail.com>"]

[workspace]
members = ["data", "data/migration", "data/entity"]

[workspace.dependencies]
uuid = { name = "1.2.0" }

[dependencies]
data = { path = "./data" }
